/* musical-terms.js — curated vocabulary for the recital-program spell checker.
 *
 * Replaces the full German and French Hunspell dictionaries (2.3 MB, ~4.1 s of
 * blocking parse time) with the vocabulary that actually appears in Conservatory
 * repertoire. Two sources:
 *   1. Every word that the German/French dictionaries rescued across 204 real
 *      form submissions (704 words) — so behavior matches the old build exactly
 *      on real historical data.
 *   2. A hand-curated set of standard musical vocabulary — Baroque dance
 *      movements, forms, tempo/expression marks, instrument names, and common
 *      German/French title words — so new repertoire is covered too.
 *
 * Matching is case-insensitive; entries are lowercased at load.
 * To add a term, just append it to the array.
 */
window.MUSICAL_TERMS = [
  "Abschied", "accelerando", "Acht", "affettuoso", "Agitato", "agitato", "ailes", "ailles",
  "Alborada", "Albumblatt", "Alessandro", "Alexa", "Alexandre", "alla", "allais", "Allemande",
  "allo", "Alten", "alten", "amabile", "Ambrose", "Ame", "Amor", "amoroso", "Amour",
  "Analogique", "andalous", "Andantino", "Andreas", "André", "anges", "animato", "Animé",
  "Antonin", "anxiété", "Appassionato", "appassionato", "Appel", "Apres", "Après", "Aquarelle",
  "Arabesque", "Arabesques", "Arad", "arbres", "Aria", "Arie", "Ariette", "Ariettes", "Arioso",
  "Arles", "artig", "assai", "Assez", "Aubade", "aube", "auch", "Audiences", "Auf", "auf",
  "Augen", "Augustin", "auréole", "Aus", "aus", "Ausdruck", "Automne", "avaient", "Avant",
  "Avec", "aventure", "Babillarde", "Bachs", "Badinerie", "Bagatelle", "Bagatellen", "Bajazet",
  "Ballade", "Ballades", "Banalités", "Bandoneon", "Barcarolle", "basson", "Basson", "bateau",
  "Batucada", "Beau", "Beeren", "Beethovens", "Bei", "Beignets", "bekam", "Bekehrte", "Belle",
  "ben", "Benedetto", "Berceuse", "Berlioz", "Bernhard", "betrübte", "Bewegt", "bewegt",
  "Bien", "bist", "blanc", "blanche", "bleu", "Bleue", "Bleus", "Blockflote", "Blockflöte",
  "Blume", "Blumen", "boire", "bois", "Bois", "Bon", "bondissante", "Bonis", "bonne", "bons",
  "Bourree", "Bourrée", "Bourrées", "Brahms", "Branle", "Bratsche", "Brillance", "brillante",
  "brio", "Brisa", "Bruch", "Bruyeres", "Bruyères", "Brèves", "Buch", "Bête", "Böhme", "bösen",
  "Cadenza", "Cadix", "calme", "campo", "Canarie", "cantabile", "Cantilène", "Canzone",
  "Capriccio", "Caprice", "Capucines", "carafon", "Cathedrale", "Cathédrale", "Cavatina",
  "Cembalo", "Centre", "cessé", "Chaconne", "Chai", "Chakra", "Chanson", "Chansons", "Chant",
  "Chants", "Chasse", "Chausson", "chemins", "Cheminée", "cher", "chevaux", "Chevaux",
  "Cheveux", "Chez", "Chopins", "Chor", "Choral", "Choralvorspiel", "Christoph", "Chu",
  "Chênes", "ciel", "Ciel", "Cierge", "Cimes", "Cinq", "Clair", "clair", "Clarinette",
  "Clavecin", "clos", "Coda", "Coeur", "Colombe", "colore", "comme", "con", "Concertino",
  "Connor", "Continuo", "continuo", "Coplas", "Cortège", "couler", "Courante", "Courte",
  "Cramer", "crescendo", "Cri", "Cupidon", "cygne", "Cygne", "Czardas", "Cécile", "César",
  "Cœur", "dai", "dal", "Damase", "Dans", "dans", "Danse", "Danses", "Debussys", "Defunte",
  "Dein", "deine", "deinen", "delicato", "della", "dello", "dem", "denk", "deux", "Deux",
  "Diable", "Dichterliebe", "dieses", "diminuendo", "Dimitri", "Divertimento", "dolce",
  "Dolcissimo", "dolente", "Domenico", "Donc", "Double", "Doucette", "Drei", "Dring", "Dritte",
  "Duc", "Duette", "Duetto", "Dukas", "Dulcinée", "Duparc", "Durchaus", "durft", "Dvorák",
  "Déclamé", "Défunte", "départ", "dürft", "e-book", "eau", "Eaux", "Egon", "eilt", "Einer",
  "Einfach", "Einfältiges", "Elegie", "Elegy", "embrumée", "emportement", "energico",
  "Engloutie", "Ensemble", "Ensemble-", "Entree", "entretiens", "Entrée", "erdacht", "erkenn",
  "Erlkonig", "Erlkönig", "Erste", "Espagne", "espagnol", "Espagnole", "espressivo",
  "Estampes", "Ete", "Etude", "Etudes", "Etwas", "Eugène", "ewiger", "expressif", "exquise",
  "Extase", "Fagnes", "Fagott", "Fantaisie", "Fantasia", "Fantasie", "Fantasien", "Faune",
  "Faure", "Fauré", "Felsen", "ferma", "Ferma", "Fernande", "Feu", "Feuer", "feuilles",
  "Feurig", "Fille", "Filles", "Finale", "Fleur", "fleurs", "Fleurs", "Flore", "Flote",
  "Flute", "Flöte", "Flöten", "Flûte", "Folies", "Fontaine", "Forelle", "Forlane", "forma",
  "Forme", "Forêt", "François", "Frauenliebe", "Fremde", "freu", "Freund", "Friedrich",
  "Fruhling", "Frédéric", "Frühling", "Frühlingsnacht", "Fuga", "Fuge", "Fugue", "funebre",
  "Funf", "funèbre", "Fur", "furioso", "féerique", "Fêtes", "Fünf", "für", "Für", "Gabe",
  "Galant", "galantes", "Galop", "gamba", "Gaspard", "Gavotte", "gebt", "geh", "Geige",
  "Geigen", "Gemma", "Georg", "Gerhard", "Gesang", "Gesange", "gesänge", "Gesänge", "Giacomo",
  "Gibet", "Gigue", "Gilles", "giocoso", "Giorgio", "giorno", "glaub", "Gluck", "Glücke",
  "Gounod", "Gracioso", "Grand", "Grande", "grandes", "grandit", "Graz", "Gretchen", "Griffes",
  "Grillon", "grolle", "Grosse", "grün", "Gustave", "Gärten", "Géranium", "hab", "hab'",
  "Habanera", "habt", "Hahn", "Haken", "Harald", "Harfe", "Harpe", "harpée", "hatt",
  "Hautbois", "hautbois", "Heftig", "Heidenröslein", "Heil", "heiligen", "Heimweh", "helle",
  "Henrique", "Herbst", "Hermann", "Herz", "Herzen", "Heure", "Heures", "heures", "hiermit",
  "Hindoue", "hip-hop", "Histoires", "Hiver", "hiver", "Hommage", "Hommages", "hor", "Horloge",
  "Horner", "hotline", "Hou", "https", "Humoreske", "Humoresque", "Hymne", "hätt", "hébraïque",
  "Hôtel", "hör", "Hör'", "hört", "ich", "Ich", "Ihr", "Images", "Immer", "Impromptu",
  "Impromptus", "Impératrice", "Indios", "Infante", "Innig", "Intermezzi", "Intermezzo",
  "Intermède", "Interstellaire", "Introduzione", "irdische", "ist", "Ivette", "Jamais",
  "Jardin", "jardin", "Jardins", "Javanaise", "Jean-Michel", "jeune", "Jeune", "Jeux",
  "Jongleurs", "José", "Jour", "jour", "Journée", "Joutes", "joyeuse", "Jüngling", "Kahn",
  "Kai", "Kannen", "keuschen", "Klarinette", "Klavier", "Klavierstuck", "Klavierstück",
  "Klavierstücke", "Klaviertrio", "kleinen", "klingen", "Knaben", "Kocher", "komm", "konnt",
  "Kontrabass", "Korrigan", "Kraftig", "Kreisleriana", "Kreutzer", "Kräftig", "Königin",
  "können", "könnt", "kühle", "Laisse", "Lamento", "lamentoso", "langoureuse", "langsam",
  "Langsam", "Larghetto", "larme", "larmes", "lass", "lasst", "Laudatio", "Leben", "Lebhaft",
  "legato", "leggiero", "Lehmann", "Leicht", "leicht", "Leidenschaftlich", "lente", "lester",
  "leuchtenden", "Lev", "libitum", "Lieb", "Liebe", "Lieben", "liebt", "Lied", "Liedchen",
  "Lieder", "Liederkreis", "Lilie", "Lin", "Linos", "Liszts", "Lointains", "los", "Loure",
  "Luca", "Lucerne", "luit", "Lukas", "Lune", "lune", "Luo", "Lyrisches", "Légende", "Léo",
  "machen", "Madchen", "Maddie", "Maestoso", "maestoso", "malabar", "Manitou", "Manon",
  "Marais", "marcato", "marche", "Marche", "Marches", "Maronne", "Marsch", "marziale",
  "Massenet", "Massig", "Matin", "Mazurka", "Mazurkas", "Megumi", "mein", "Mein", "meine",
  "Meine", "meinen", "Meins", "Melodie", "Melodien", "meno", "Menschen", "menuet", "Menuet",
  "Mer", "messagère", "mezzo-soprano", "Mignonne", "Milde", "Milhaud", "Minuet", "mir",
  "Miroirs", "misterioso", "mit", "Mit", "mocht", "Modo", "Modéré", "Moins", "mon", "Monat",
  "Mond", "Mondnacht", "Montréal", "Morceau", "Morgen", "Mort", "mort", "morte", "mosso",
  "moto", "Moto", "Mouvement", "Mozarts", "Munter", "Musette", "musiciens", "Musique", "musst",
  "Myrthen", "Mädchen", "Märchen", "Mässig", "Mäßig", "Méditation", "Mélodie", "Mélodies",
  "Ménestrel", "möcht", "müsst", "Nach", "Nachspiel", "Nacht", "Nana", "Naturelles", "Nebel",
  "nehmt", "Neige", "nel", "nella", "neu", "Neuling", "Neun", "nicht", "Nicht", "Nino",
  "Nocturne", "noir", "noires", "notre", "Notturno", "Nouveau", "Nouvelle", "Novelette",
  "Novelletten", "Nuages", "nuit", "Nuit", "nur", "nymphée", "Oboe", "oder", "Offrande",
  "Ohne", "Oiseau", "Oiseaux", "ombre", "Ombre", "Ondine", "Orchestre", "Ordre", "Orgel",
  "Orgue", "Oskar", "ostinato", "oubliées", "Ouverture", "Ouvre", "Paganini", "Paganini's",
  "Paganinis", "Pagodes", "Paille", "Panini", "Paola", "Paon", "Papillons", "Par", "parler",
  "Partita", "Parton", "Passacaglia", "Passepied", "pastorale", "Pastorale", "Pathétique",
  "Pavane", "perf", "Perf", "perfides", "Pesante", "pesante", "Petersburg", "Petit", "Petite",
  "peur", "Pferden", "Pfister", "Phantasie", "phantastisch", "Philipp", "pince-sans-rire",
  "Pintade", "Piotr", "piu", "Pièce", "Pièces", "più", "Plagal", "pleure", "pleut", "plonges",
  "pluie", "Pluie", "Plus", "Poeme", "Poissons", "Polonaise", "porque", "Posaune", "poserai",
  "Poulenc", "Pour", "Poème", "Poèmes", "Praeambulum", "Praeludium", "Prelude", "Preludio",
  "Première", "presque", "prima", "primo", "Printemps", "Prix", "Prolog", "Près", "Prélude",
  "Préludes", "Psy", "Puisque", "Pur", "Pâques", "pénombre", "Quand", "Quartett", "Quartetto",
  "quasi", "Quatre", "que", "Quelle", "qui", "Quichotte", "Quinten", "Quintetto", "qué",
  "Rameau", "Rasch", "Rastlose", "Raum", "Ravels", "Rebecca", "Recitativo", "Reflets", "reine",
  "religioso", "René", "Reste", "Reve", "rhapsodie", "Rhapsodie", "Rhapsody", "Rhein",
  "Ricercar", "rien", "Rigaudon", "risoluto", "ritardando", "Ritornello", "rivière", "Roches",
  "roi", "Roi", "Romance", "Romances", "Romanze", "Romanzen", "Rondeau", "Ronsard", "rosa",
  "Rose", "Roslein", "rubato", "Ruhig", "Rustique", "Rustiques", "Récitatif", "Rêve",
  "Röslein", "Sacrée", "sag", "sags", "Saint", "Saint-Saëns", "Sainte", "Sanglots", "Sans",
  "Sarabande", "Satie", "Saudade", "Saëns", "Scarbo", "Scarlett", "Schafe", "Schatten",
  "scherzando", "Scherzando", "Scherzen", "Scherzi", "Scherzo", "Schlagende", "schlimme",
  "Schnake", "schnell", "Schnell", "schnellen", "Schon", "Schuberts", "Schumanns", "SEAMUS",
  "Sechs", "seconda", "secondo", "Seele", "Seguidilla", "seh", "seh'", "Sehnsucht", "Sehr",
  "seht", "sei", "seid", "Sein", "semplice", "sempre", "Sentier", "Sentimentale", "sera",
  "Serenade", "Sestetto", "sforzando", "sich", "Sich", "sicher", "Siciliana", "Sicilienne",
  "Sieben", "Silvio", "Silène", "singen", "Singstimme", "Sinn", "soir", "Soir", "soirée",
  "Solaris", "Soldat", "Soldaten", "Soledad", "Soleil", "sollt", "Sombre", "sommeil", "Sommer",
  "Sonatas", "Sonate", "Sonatina", "Sonatine", "Sonne", "Sorge", "sorte", "Sostenuto",
  "sostenuto", "sotto", "Sous", "Spanisches", "Spiegel", "Spinnrade", "sprießen", "Spröde",
  "staccato", "Stadt", "Standchen", "steh", "Stern", "Sterne", "Stimme", "Streichquartett",
  "Stuck", "Ständchen", "Stéphane", "Stück", "Stücke", "subito", "Suite", "sur", "Sur",
  "Symphonique", "Syrinx", "Série", "Sérénade", "Séville", "Takeshi", "Tambourin", "Taube",
  "tauchen", "tausend", "tempi", "tempo", "Temps", "tendre", "Tendresse", "terra", "Terrasse",
  "Terzetto", "tes", "Thaïs", "Thierry", "Thron", "Thème", "Théo", "Tian", "tiefe", "Tobias",
  "Toccata", "Tod", "Toujours", "Tournez", "tournez", "tous", "toutes", "tranquillo", "Traum",
  "Traurigkeit", "travelling", "travers", "Traversiere", "Tres", "tret", "triste", "Triste",
  "Trois", "Trombone", "Trompete", "Trompette", "Tränen", "Très", "Töne", "Uber", "Und", "Une",
  "Ungar", "Unter", "Vals", "Valse", "valse", "Valses", "Variationen", "Variations", "Variée",
  "Veilchen", "Vent", "venta", "Vers", "vers", "verschiedener", "Vida", "Vie", "Vier",
  "Vierte", "Vieux", "Vif", "Villanelle", "ville", "Vincenzo", "Violine", "Violon",
  "Violoncelle", "Violoncello", "Violone", "Violons", "vivo", "Vivo", "Vocalise", "voce",
  "Vogel", "Voici", "Voix", "Volker", "Von", "Vor", "Vorspiel", "Vortrage", "vorzutragen",
  "Vos", "Vox", "vérité", "Völker", "Wagners", "Wai", "Wald", "Waldesgespräch", "Wallonie",
  "Wanderer", "war", "Wasser", "weiden", "weiss", "weiß", "Wenn", "Wer", "Widmung", "Wie",
  "Wieder", "wieder", "Winter", "Winterreise", "Wir", "wir", "wird", "wollt", "wunderschönen",
  "www", "Wyandotte", "wär", "Xiang", "Yeux", "yeux", "Zach", "Zart", "zartem", "Zehn",
  "zieht", "Ziemlich", "Zufriedenheit", "Zwei", "Zweite", "Zwischen", "Zwischenspiel", "Âme",
  "Élégie", "énamourée", "épique", "étaient", "Étude", "Études", "été", "Été", "üben", "über",
  "Über"
];
